### PR TITLE
Clean up shadowed/unused warnings

### PR DESCRIPTION
**Pull request by zenspider**

### CODE REVIEW

**Comment by zenspider** [comment]
Also see my HACK tag in my diff. I think the variable usage inside the block is potentially incorrect.

**Comment by zenspider** [comment]
_ping_

I'd like to see this get released if possible.

**Comment by ahoward** [comment]
blargh - sorry this dropped through the cracks.  @zenspider  i'm adding you to the repo so it won't happen again.

**Comment by ahoward** [comment]
done.  thanks!

**Pull request merged**
